import type { Metadata } from "next";
import { Merriweather, Jost, Geist } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import React from "react";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={cn("h-full", "antialiased", merriweather.variable, jost.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">
          <AppRouterCacheProvider>
              {children}
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
